- id: '1578943476911'
  alias: Termo
  description: ''
  trigger:
  - at: '23:30'
    platform: time
  condition: []
  action:
  - entity_id: switch.unnamed_device
    service: switch.turn_on
  - delay: '10:00'
  - entity_id: switch.unnamed_device
    service: switch.turn_off
- id: '1581423441740'
  alias: Caixa de correo
  description: ''
  trigger:
  - entity_id: sensor.caixa_de_entrada
    from: '0'
    platform: state
    to: '1'
  condition:
  - after: 08:30
    before: '23:45'
    condition: time
  action:
  - data:
      message: Consulta a caixa de correo, tés unha nova mensaxe.
      title: Novo correo electrónico
    service: notify.mobile_app_lm_g710
- id: '1582584926447'
  alias: kodi
  description: ''
  trigger:
  - at: '19:58'
    platform: time
  condition: []
  action:
  - data:
      data:
        message: Faltan 2 minutos para aplaudir
        title: Aviso importante
    service: notify.kodi
  - delay: 00:02:00
  - data:
      message: Xa é horta
      tittle: Aviso importante
    service: notify.kodi
  - data: {}
    entity_id: media_player.kodi
    service: media_player.media_pause
  - delay: 00:02:00
  - data: {}
    entity_id: media_player.kodi
    service: media_player.media_play
- id: '1585249766053'
  alias: Batería
  description: ''
  trigger:
  - entity_id: sensor.battery_level
    from: '99'
    platform: state
    to: '100'
  condition: []
  action:
  - data:
      message: Xa está a batería a tope, podes descargarme
    service: notify.mobile_app_lm_g710
