# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

#Transporte

sensor: !include_dir_merge_list sensors/

logger:
  default: critical
  logs:
    homeassistant.components.http.ban: warning

# Camaras

camera:
  - platform: ffmpeg
    input: rtsp://192.168.0.20/live/ch00_1

# Termostato 

climate:
  - platform: hysen
    devices:
      main_thermostat:
        name: Termostato_comedor
        host: 192.168.0.18
        mac: !secret Termostato

# Días laborables

binary_sensor:
  - platform: workday
    country: ES
    province: GA
    add_holidays:
    - '2020-03-20'
    - '2020-08-16'

  - platform: "mqtt"
    state_topic: "zigbee2mqtt/SensorMovemento"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.occupancy }}"
    device_class: "motion"

  - platform: "mqtt"
    state_topic: "zigbee2mqtt/MovementoBannoAzul"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.occupancy }}"
    device_class: "motion"

# Reprodutor multimedia

media_player:
  - platform: kodi
    host: 192.168.0.10
    name: kodi
    username: !secret kodi
    password: !secret ctrsnlkodi
    port: 8081

# HUE

emulated_hue:
  host_ip: 192.168.0.23
  listen_port: 80
  exposed_domains:
    - light
    - media_player
    - switch
    - climate

# MQTT

mqtt:
  broker: !secret urlMQTT
  port: !secret portMQTT
  client_id: home-assistant
  discovery: true
  discovery_prefix: homeassistant
  username: !secret usuarioMQTT
  password: !secret ctrsnlMQTT
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

# Zonas

zone: !include zones.yaml

switch:
  - platform: orvibo
#    discovery: false
#    switches:
#      - host: 192.168.0.11
#        mac: !secret TermoMAC
#        name: "Termo"

  - platform: rest
    resource: http://192.168.0.23:8126/container/MQTT
    name: MQTT
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

  - platform: mqtt
    name: "Luz_banno_azul"
    state_topic: "stat/Sonoff_banno_azul/POWER"
    command_topic: "cmnd/Sonoff_banno_azul/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Luz_banno_marron"
    state_topic: "stat/Sonoff_banno_marron/POWER"
    command_topic: "cmnd/Sonoff_banno_marron/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

shell_command:
  restart_hass: 'curl http://192.168.0.23:8126/container/home-assistant/restart'

# Avisos

notify:
  - name: JabberJavi
    platform: xmpp
    sender: !secret xmppfogar
    password: !secret ctrsnlfogar
    recipient: !secret meuxmpp

  - name: JabberRA
    platform: xmpp
    sender: !secret xmppfogar
    password: !secret ctrsnlfogar
    recipient: !secret raxmpp

  - name: MeuMail
    platform: smtp
    server: !secret svrmeumail
    port: 25
    username: !secret meumail
    password: !secret ctrsnlmail
    timeout: 15
    sender: !secret meumail
    recipient: !secret mailnotificacion
    sender_name: Fogar

  - name: kodi
    platform: kodi
    host: 192.168.0.10
    username: !secret kodi
    password: !secret ctrsnlkodi
    port: 8081

  - platform: nfandroidtv
    name: TV
    host: 192.168.0.10

# HACS
hacs:
  token: !secret tokenHACS

# Text to speech
tts:
  - platform: google_translate
    language: es

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
